### ISSUE TITLE
How to update Username After Creation?

### ISSUE THREAD

**Issue by firrae** [copleykj/socialize-user-profile#12]
Curious how you can change the username field after the document has been created? When I try to I just get:
```
Exception while invoking method 'profile.setUsername' Error: Username cannot be set during an update in socialize:profiles update
```

Is this due to the `custom: SimpleSchema.denyUntrusted` line? If so how would I make the user that owns the profile "trusted"?

**Comment by copleykj** [comment]
Currently, the package limits changing the username field to trusted code (server executed). The thought here is that since the username comes from the `User` document that it shouldn't be changed arbitrarily from the client without updating the document in the `Meteor.users` collection as well.

If this isn't an issue for your application, you should be able to attach another schema containing only the definition for the offending field, and it should overwrite the previous one. If you want to keep this limitation but still want to change the username, you could set up a method that runs on the server to change it.

**Comment by firrae** [comment]
Ah, ok. I am using social logins so there is no username by default it seems (at least for Facebook and Twitter) so I was planning to have users select their names after the fact. I'll look at either overriding the field or just making a new one to use.

**Comment by firrae** [comment]
Hm, maybe there's something I'm missing? This is my expansion to the default Profile:
```
import { Meteor } from 'meteor/meteor';
import { Profile, ProfilesCollection  } from 'meteor/socialize:user-profile';
import SimpleSchema from 'simpl-schema';

Profile.attachSchema(new SimpleSchema({
    "screenname": {
        type: String,
        index: true,
        unique: true,
    }
}));

Profile.methods({
    setScreenname(name) {
        if(Meteor.isServer) {
            console.log(name);
            console.log(Profile);
            ProfilesCollection.update({_id: this.userId}, {$set: {screenname: name}});
            // this.screenname = name;
            // console.log(Profile.validate(this));
            // console.log(this.save());
            console.log(ProfilesCollection.findOne(this.userId));
            return "success?";
        } else {
            throw Error("This action is only available on the server!");
        }
    }
});
```

I realize now that `Profile` is a class so `validate()` isn't available, but is there a way to set things? My attempt to use the collection to run an update seems to either be failing silently, or not doing anything?

It's been a while since I've used Meteor, so maybe it's obvious, but I'm not understanding what I'm missing.

**Comment by copleykj** [comment]
This should be dead simple.

1. Attach a schema with the updated username field.
2. Make sure that the user profile document is published to the client.
3. Get a reference to the user profile
4. update the property on the user profile
5. call the save method on the user profile.

Somewhere on the server
```js
import { Profile } from 'socialize:user-profile';
import SimpleSchema from 'simpl-schema';

Profile.attachSchema(new SimpleSchema({
  username: {
    type: String,
    index: 1,
    unique: true,
    optional: true,
  },
}));
```

Somewhere on the client
```js
const user = Meteor.user();

Meteor.subscribe('socialize.userProfile', user.username);

const profile = user.profile();

profile.username = "SomeUniqueUsername";
profile.save();
```

**Comment by firrae** [comment]
When I try something like this:
```
import { Meteor } from 'meteor/meteor';
import { Profile, ProfilesCollection  } from 'meteor/socialize:user-profile';
import SimpleSchema from 'simpl-schema';

Profile.attachSchema(new SimpleSchema({
    "screenname": {
        type: String,
        index: true,
        unique: true,
    }
}));

Profile.methods({
    setScreenname(name) {
        if(Meteor.isServer) {
            console.log(name);
            console.log(Profile);
            console.log(Meteor.user().profile());

            let target = Meteor.user().profile();
            console.log('setting username');
            target.screenname = name;

            target.save(function(r) {
                console.log(r);
            });
            console.log('tried saving');
            // console.log(ProfilesCollection.findOne(this.userId));

            return "success?";
        } else {
            throw Error("This action is only available on the server!");
        }
    }
});
```

I'm calling it through a method like so:
```
Meteor.methods({
    'profile.setUsername': (name) => {
        // console.log(this.userId);
        // console.log(Meteor.user().profile());
        const result = Meteor.user().profile().setScreenname(name);
        // console.log(Meteor.user().profile());
        return result;
    }
});
```

I get this as my result:
```
"Error: You don't have a schema defined for socialize:profiles [noSchema]
    at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=9e4081c1b0dfde446688af96b8d9e8494e67fe2a:1792:23)
    at Connection.onMessage (http://localhost:3000/packages/ddp-client.js?hash=9e4081c1b0dfde446688af96b8d9e8494e67fe2a:1958:12)
    at http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:216:11
    at Array.forEach (<anonymous>)
    at ClientStream.forEachCallback (http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:297:31)
    at SockJS.socket.onmessage (http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:215:14)
    at SockJS.REventTarget.dispatchEvent (http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:545:22)
    at SockJS._dispatchMessage (http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:1730:10)
    at SockJS._didMessage (http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:1800:16)
    at WebSocket.that.ws.onmessage (http://localhost:3000/packages/socket-stream-client.js?hash=50e1fc1ec576cba39c38336d2bd55ba023e60bc6:1958:15)"
```

Am I missing something? This is included on the server side. I even tried putting it in the server side startup but I get the same outcome. This will be something stupid I know, but I'm completely lost. It stops directly before trying to set the screenname according to the server output.

**Comment by firrae** [comment]
The issue with your example is that the account I made using Facebook oAuth doesn't have a username by default it seems:

```
Profile {
  _id: 'siTL42JYzp5WQRvio',
  createdAt: 2021-02-19T03:08:52.167Z,
  updatedAt: 2021-02-19T03:08:52.167Z,
  getDocument: [Function: getDocument]
}
```

The created user via Facebook:
```
I20210218-23:03:36.459(-5)? User {
I20210218-23:03:36.460(-5)?   _id: 'siTL42JYzp5WQRvio',
I20210218-23:03:36.460(-5)?   createdAt: 2021-02-19T03:08:52.157Z,
I20210218-23:03:36.461(-5)?   services: {
I20210218-23:03:36.461(-5)?     facebook: {
I20210218-23:03:36.461(-5)?       accessToken: '<token>',
I20210218-23:03:36.461(-5)?       expiresAt: 1618887989656,
I20210218-23:03:36.461(-5)?       id: '<id>',
I20210218-23:03:36.461(-5)?       email: 'me@hotmail.com',
I20210218-23:03:36.462(-5)?       name: 'Steve Lambe',
I20210218-23:03:36.462(-5)?       first_name: 'Steve',
I20210218-23:03:36.462(-5)?       last_name: 'Lambe',
I20210218-23:03:36.462(-5)?       name_format: '{first} {last}',
I20210218-23:03:36.462(-5)?       picture: [Object],
I20210218-23:03:36.462(-5)?       short_name: 'Steve'
I20210218-23:03:36.463(-5)?     },
I20210218-23:03:36.463(-5)?     resume: { loginTokens: [Array] }
I20210218-23:03:36.463(-5)?   },
I20210218-23:03:36.463(-5)?   getDocument: [Function: getDocument]
I20210218-23:03:36.463(-5)? }
```

**Comment by copleykj** [comment]
> The issue with your example is that the account I made using Facebook oAuth doesn't have a username by default it seems;

This code should still work to add the username after creation. The fact that it is saying that the collection doesn't have a schema attached is very strange though. Do you have the app source available where I could clone it for debugging?

**Comment by firrae** [comment]
@copleykj I'll make it public, give me a moment

**Comment by firrae** [comment]
@copleykj https://github.com/Firrae-Technologies/artiststales. You'll have to provide your own FB keys, or I can more privately give you mine if you need.

I'll have to make it private again after if you are looking at this in the future.

**Comment by copleykj** [comment]
Ok, hmm.. I'll have to see about what it takes to create those.. For now, I've got to get some sleep, but I'll get to debugging this ASAP in the morning.

**Comment by firrae** [comment]
@copleykj that's cool. It's fairly simple if you have a FB account. Head to developers.facebook.com, log in, create an "app", add "login with Facebook" and follow the prompts. Then under settings (I think they might appear before) you should see: 
![Capture](https://user-images.githubusercontent.com/6454839/109256710-9c080a00-77c4-11eb-813f-d00e91e76bf1.PNG)

You'll need the AppId and Secret to plug into my `useraccounts-configuration.js` file.

If you don't have an account, I can give you mine I just don't want to blast them publicly if I can help it.

I'm also still not throwing out the idea I've done something dumb to cause this. It's been a while since I was in Meteor development to any degree, and things have changed a lot lol.

**Comment by copleykj** [comment]
Ok, I think the issue here is that you need to update all of your socialize packages to the latest versions. The most recent version of `simpl-schema` contains changes that are incompatible with the version of `socialize:base-model` that is currently installed in your project. This issue was fixed in `socialize:base-model@1.1.5` and from your .packages file shows that 1.1.3 is installed.

**Comment by copleykj** [comment]
I've tried upgrading packages in the project to make sure this would go smoothly for you. Unfortunately, there were a bunch of dependency versions that the constraint solver didn't like putting together. From what I can tell it seems to stem from grapher having a dependency on an older version of collection-hooks. From what I remember the newer version is compatible but grapher hasn't seen an update in a couple years. To get your project into a working state I think the easiest course will be modifying the .meteor/packages file to the following:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.1.0       # Packages for a great mobile UX
mongo@1.10.1                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-js@2.6.0    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.15.0              # Enable ECMAScript2015+ syntax in app code
typescript@4.1.2              # Enable TypeScript syntax in .ts and .tsx modules
shell-server@0.5.0            # Server-side component of the `meteor shell` command

insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
svelte:compiler
rdb:svelte-meteor-data
static-html
aldeed:collection2
cultofcoders:grapher
dburles:collection-helpers
accounts-base
accounts-password
accounts-facebook
accounts-google
accounts-twitter
quave:accounts-apple
alanning:roles
service-configuration
hexsprite:postcss
matb33:collection-hooks@1.0.1!
socialize:user-profile@1.0.4!
socialize:feed@1.0.4!
socialize:postable@1.0.3!
socialize:user-blocking@1.0.5!
socialize:friendships@1.1.1!
socialize:base-model@1.1.6!
```

Once the project finishes updating the dependencies, I believe you should be able to remove the exclamation marks from the end of all the socialize packages, but the one on collection-hooks will need to stay unless grapher gets updated to depend on the newer version.

**Comment by copleykj** [comment]
So apparently that doesn't actually work. Meteor acts like it updates the packages and even lists them with their updated versions when you run `meteor list --tree` but it doesn't actually update them :facepalm:

**Comment by copleykj** [comment]
haha, well now I just feel like an idiot.. I've apparently not published that fix...

**Comment by copleykj** [comment]
Ok, so I have published that update and I have it working properly by using the `.meteor/packages` file posted above.

**Comment by firrae** [comment]
Haha, awesome. I'll check it out tonight. Thanks a bunch for looking into this and even identifying the issue with updating I hadn't gotten to yet. I'll likely remove Grapher as I added it as I thought I might need it before finding all the Socialize packages (namely the Feed and Posts with comments and such). I hope to be able to give back in some way moving forward once I have the project complete as you are essentially doing a lot of my heavy lifting with these packages lol.

As I dig in more to how your stuff is working, I'll keep and eye on tickets and such that come up and try and pitch in where I can, and hopefully sooner than later offer some sort of financial contribution as these seem like great packages, and you clearly offer great support for them.

**Comment by firrae** [comment]
Guess I'll need to wait to try this. Atmosphere is telling me that 1.1.5 is the newest it can find O.o Even trying `meteor add socialize:base-model@1.1.6` returns `error: no such version socialize:base-model@1.1.6` lol. I guess I'll try it later tomorrow. Hopefully this is just a cache issue or something as it also thinks I'm behind a proxy due to being on WSL2.

**Comment by copleykj** [comment]
> error: no such version socialize:base-model@1.1.6

This is very strange. Try running `meteor show socialize:base-model` first and see if it's in the versions list.

**Comment by firrae** [comment]
```
Recent versions:
  1.1.1_1  February 8th, 2018
  1.1.2    February 13th, 2018
  1.1.3    May 27th, 2018        installed
  1.1.4    August 7th, 2020
  1.1.5    August 17th, 2020     installed
```

But I really think the issue is with:
```
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
```

I'm developing in WSL2, so I wonder if it's getting messed with as it goes through Windows to get to the internet.

**Comment by copleykj** [comment]
Yeah, not being able to make a connection to the package servers could be an issue lol.. Unfortunately, I don't have any experience on the windows side of Meteor development, so I wouldn't be any help in that respect.

**Comment by firrae** [comment]
I have solved it. Apparently my Ubuntu instance's internal clock had drifted and needed to be forcibly updated to match the hardware clock. Weird issue that is apparently know to WSL2, but causes all sorts of weird errors it seems.

**Comment by copleykj** [comment]
Awesome, glad it's working again!

**Comment by firrae** [comment]
Yup, just tested. All looks good. Thanks a bunch for helping with this!
