### ISSUE TITLE
Required items in the schema

### ISSUE THREAD

**Issue by fahadakhan96** [copleykj/socialize-user-profile#7]
Do all attributes that I append to the schema have to be optional? Currently, it throws an error when the profile document is being created since one can't provide the required attributes when the profile is being created. Maybe you could update the code to set all the required items to null when the document is being created?

**Comment by copleykj** [comment]
Instead of optional, you could set default values for each field. I'm thinking though that maybe automatic profile creation should be optional. I'll see about getting it into the next release.

**Comment by copleykj** [comment]
Automatic profile can be disabled in the next release.
